---
version: 1
template: app-ecs
runtime: python37
Parameter:
    - Projeto: Pipeline-Python
pipeline:
    - source:
        - BranchName: master
        - RepositoryName: App
    - ci
    - security
    - publish
    - custom::Seguranca:
        - seguranca1:
            - source: Build
            - environment:
                - Name : chave
                - Value: valor
            - imagecustom: linuxcustom
            - runorder: 1
        - seguranca3:
            - source: Build
            - environment:
                - Name : chave
                - Value: valor
            - imagecustom: linuxcustom
            - runorder: 2           

    - custom::Segurancaf:
        - seguranca2:
            - source: Build
            - environment:
                - Name : chave
                - Value: valor
            - imagecustom: linuxcustom
            - runorder: 1           

    - deploy
