---
version: 1
template: app-ecs
runtime: python37
Parameter:
    - Projeto: Pipeline-Python
    - Branch: master
pipeline:
    - source:
        - BranchName: master
        - RepositoryName: App
    - ci
    - security
    - publish
    - deploy
