---
version: 1
template: app-ecs
runtime: python37
provider: aws
Parameter:
    - Projeto: Pipeline-Python
pipeline:
    - Source
    - Continuou_Integration
    - Deploy
callback:
    protocolo: email
    endpoint: clodonil@nisled.org
