---
Description: Estrutura do pipeline customizada
AWSTemplateFormatVersion: '2010-09-09'

Resources:

  DyPipelines:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pipeline-custom-templates
      AttributeDefinitions:
        - AttributeName: name
          AttributeType: S
      KeySchema:
        - AttributeName: name
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DyMetricas:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pipeline-custom-metricas
      AttributeDefinitions:
        - AttributeName: account
          AttributeType: S
        - AttributeName: resource_id
          AttributeType: S
      KeySchema:
        - AttributeName: account
          KeyType: HASH
        - AttributeName: resource_id
          KeyType: RANGE  

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  DyStacks:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: pipeline-custom-stacks
      AttributeDefinitions:
        - AttributeName: account
          AttributeType: S
        - AttributeName: stacks
          AttributeType: S
      KeySchema:
        - AttributeName: account
          KeyType: HASH
        - AttributeName: stacks
          KeyType: RANGE  

      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: pipeline-custom-templates